import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matthew Mocniak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="mx-72 mt-12">
          <h1 className="text-5xl font-bold text-gray-800">
            Matthew Mocniak
          </h1>
          <h2 className="mt-8 text-2xl text-gray-600">
            I'm a product designer who has a keen attention to detail. I love working closely with other designers and developers to deliver excellent products and experiences.
          </h2>
        </div>
      </main>
    </div>
  )
}
